/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jasacs;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author 1412625
 */
public class StudentsAssessmentVersionBoard extends javax.swing.JDialog {
   public ClassLocationObject clo;
    List<ClassLocationObject> depClosQue;
    DefaultListModel<String> dlm = new DefaultListModel<>();
    String currentAssessment;
    String studAsPath;
    String studMatric;
    /**
     * Creates new form StudentsAssessmentVersionBoard
     */
    public StudentsAssessmentVersionBoard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);  
        depClosQue = new ArrayList<>();
    }
    
        public StudentsAssessmentVersionBoard(java.awt.Frame parent, boolean modal, String curAs) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);               
        depClosQue = new ArrayList<>();
        currentAssessment = curAs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectedFile = new javax.swing.JTextField();
        addstudAssBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lister = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        finish = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        matricTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(StudentsAssessmentVersionBoard.class, "StudentsAssessmentVersionBoard.jLabel1.text")); // NOI18N

        selectedFile.setEditable(false);
        selectedFile.setText(org.openide.util.NbBundle.getMessage(StudentsAssessmentVersionBoard.class, "StudentsAssessmentVersionBoard.selectedFile.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(addstudAssBtn, org.openide.util.NbBundle.getMessage(StudentsAssessmentVersionBoard.class, "StudentsAssessmentVersionBoard.addstudAssBtn.text")); // NOI18N
        addstudAssBtn.setEnabled(false);
        addstudAssBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudAssBtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(StudentsAssessmentVersionBoard.class, "StudentsAssessmentVersionBoard.jPanel1.border.title"))); // NOI18N

        lister.setEditable(false);
        lister.setColumns(20);
        lister.setRows(5);
        jScrollPane2.setViewportView(lister);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(StudentsAssessmentVersionBoard.class, "StudentsAssessmentVersionBoard.jButton4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(finish, org.openide.util.NbBundle.getMessage(StudentsAssessmentVersionBoard.class, "StudentsAssessmentVersionBoard.finish.text")); // NOI18N
        finish.setEnabled(false);
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        matricTxt.setText(org.openide.util.NbBundle.getMessage(StudentsAssessmentVersionBoard.class, "StudentsAssessmentVersionBoard.matricTxt.text")); // NOI18N
        matricTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matricTxtKeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(StudentsAssessmentVersionBoard.class, "StudentsAssessmentVersionBoard.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(matricTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(selectedFile)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addstudAssBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(matricTxt)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addstudAssBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(finish))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addstudAssBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudAssBtnActionPerformed
        AssessmentFile af = new AssessmentFile();
        clo = af.getNewAssessmentFile();       
        selectedFile.setText(clo.getClassName());
        System.out.println("full class location: "+clo.getFullClassLocation());
        System.out.println("full class location: "+clo.getFullClassDetails());
        
        LocateAndAddAllDependencyForStudent lad = new LocateAndAddAllDependencyForStudent(clo.getFullClassLocation(), currentAssessment);
        for(String al : lad.listOfDependency){
            lister.append(al);
            lister.append("\n");
        }      
        finish.setEnabled(true);
    }//GEN-LAST:event_addstudAssBtnActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        studMatric = matricTxt.getText().trim();
        
        CreateDependencies cd = new CreateDependencies(clo, currentAssessment);
        Object[] ob = cd.createStudDependency(true);
        studAsPath = (String) ob[1];
        System.out.println("student assessment: "+studAsPath);
        dispose();

    }//GEN-LAST:event_finishActionPerformed

    private void matricTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matricTxtKeyReleased
                try{
        
        if(matricTxt.getText() == null | (matricTxt.getText().length() == 7)){
            int x = Integer.parseInt(matricTxt.getText().trim());
            addstudAssBtn.setEnabled(true);
            
            
        }else{
            addstudAssBtn.setEnabled(false);
        }
        }catch(Exception e){
            addstudAssBtn.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Invalid matric number");
     }
    }//GEN-LAST:event_matricTxtKeyReleased

        private void createDependencies(){
        depClosQue.add(clo);
        int c = 0;
        int threshold = 0;
        for(int i = depClosQue.size(); i > 0; i--){
            threshold += i;
        }
        System.out.println("****************************************class name:>>> "+threshold);
        while(!depClosQue.isEmpty()){
            if (c > threshold){
                JOptionPane.showMessageDialog(this, "Some Dependencies are not provided");
               break;
            }           
        c++;
        System.out.println("-----------------class name:>>> "+depClosQue.get(0).getClassName());
        ClassLocationObject x = depClosQue.remove(0);
        String sf = selectedFile.getText();
            System.out.println("outing from the text field:"+sf);
            System.out.println("outing from the clo class name:"+x.getClassName());
        CreateDependencies cd = new CreateDependencies(x, currentAssessment);
        // check if it returns true or false
        Object[] ret =  cd.createStudDependency(sf.equalsIgnoreCase(x.getClassName()));
        if(!(Boolean) ret[0]){
            depClosQue.add(x);
          }
        if((String) ret[1] != null){
            studAsPath = (String)ret[1];
            AssessObject  ao = new AssessObject(sf);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsAssessmentVersionBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsAssessmentVersionBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsAssessmentVersionBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsAssessmentVersionBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentsAssessmentVersionBoard dialog = new StudentsAssessmentVersionBoard(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addstudAssBtn;
    private javax.swing.JButton finish;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea lister;
    private javax.swing.JTextField matricTxt;
    private javax.swing.JTextField selectedFile;
    // End of variables declaration//GEN-END:variables
}
